inc:
  # Blog Information
  title:        "Máster en Innovación en Periodismo"
  subtitle:     "Máster 100% online y oficial de la Universidad Miguel Hernández"
  logo:         logo.jpg
  cover_image: cover_image.jpg
  
  # Company information
  company:      Máster en Innovación en Periodismo
  url:          http://mip.umh.es
  facebook:     mipumh
  twitter:      mipumh
  gplus:        '103906596485859350077'
  
  # Product Information
  product_link: preinscripcion.html
  tagline:      "Idea, diseña, emprende"
  
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  mipgithub
    
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    
 # Analytics     
  analytics:
    google: true

plugins: [jekyll-paginate]
permalink:     pretty